#!/usr/bin/env python3
"""
gen_wide_tables.py — Generate SQL for super-wide benchmark tables.

Creates tables with 100, 300, and 1000 columns with mixed types:
  ~60% varchar, ~20% int/bigint, ~20% mixed (boolean, numeric, timestamp)

Data is sparse: only ~10% of columns are populated per row (NULLs elsewhere).

Usage:
    python3 gen_wide_tables.py > tests/bench_setup_wide.sql
"""

CONFIGS = [
    # (name, ncols, nrows)
    ("wide_100",  100,  500000),
    ("wide_300",  300,  200000),
    ("wide_1000", 1000, 100000),
]


def col_type(i):
    """Assign type to column i (0-based).
    ~60% varchar, ~20% int/bigint, ~20% mixed (boolean, numeric, timestamp)."""
    bucket = i % 10
    if bucket < 6:
        return "varchar(40)"
    elif bucket < 8:
        return "bigint" if (i % 4 == 0) else "integer"
    elif bucket == 8:
        return ["boolean", "numeric(12,4)", "timestamp"][i % 3]
    else:
        return ["numeric(12,4)", "boolean", "timestamp"][i % 3]


def col_value_expr(i, col_t):
    """Generate a value expression for column i, with ~10% sparsity."""
    if "varchar" in col_t:
        val = f"'v' || (i % 1000)"
    elif col_t == "bigint":
        val = f"i::bigint * {(i % 7) + 1}"
    elif col_t == "integer":
        val = f"(random()*10000)::int"
    elif col_t == "boolean":
        val = f"(i % {(i % 5) + 2} = 0)"
    elif "numeric" in col_t:
        val = f"(random()*1000)::numeric(12,4)"
    elif col_t == "timestamp":
        val = f"'2020-01-01'::timestamp + (i % 1000000) * interval '1 second'"
    else:
        val = "NULL"

    # Sparse: ~10% populated.  Use deterministic hash so results are reproducible.
    # Cast to bigint to avoid integer overflow with large i values.
    prime = 7919
    return f"CASE WHEN (i::bigint*{prime}+{i}) % 10 = 0 THEN {val} END"


def cname(i, ncols):
    return f"c{i+1:04d}" if ncols >= 100 else f"c{i+1:02d}"


def generate_table(name, ncols, nrows):
    lines = []
    lines.append(f"-- {name}: {nrows} rows, {ncols} data columns + id + grp")
    lines.append(f"-- ~60% varchar, ~20% int/bigint, ~20% boolean/numeric/timestamp, ~10% populated")
    lines.append(f"CREATE TABLE IF NOT EXISTS {name} (")
    lines.append(f"    id integer,")

    col_defs = []
    for i in range(ncols):
        col_defs.append((cname(i, ncols), col_type(i)))
        lines.append(f"    {cname(i, ncols)} {col_type(i)},")

    lines.append(f"    grp integer")
    lines.append(f");")
    lines.append("")

    # Population: use INSERT .. SELECT for all sizes.
    # PostgreSQL handles statements with 1000+ columns fine.
    lines.append(f"DO $$")
    lines.append(f"BEGIN")
    lines.append(f"    IF NOT EXISTS (SELECT 1 FROM {name} LIMIT 1) THEN")
    lines.append(f"        RAISE NOTICE 'Populating {name} ({nrows} rows, {ncols+2} cols, sparse)...';")
    lines.append(f"        INSERT INTO {name}")
    lines.append(f"        SELECT i,")

    for i, (cn, ct) in enumerate(col_defs):
        val = col_value_expr(i, ct)
        lines.append(f"               {val},")

    lines.append(f"               i % 500")
    lines.append(f"        FROM generate_series(1, {nrows}) i;")
    lines.append(f"    END IF;")
    lines.append(f"END $$;")
    lines.append("")
    lines.append(f"ANALYZE {name};")
    lines.append("")
    return "\n".join(lines)


def main():
    print("-- bench_setup_wide.sql — Super-wide benchmark tables")
    print("-- Generated by tests/gen_wide_tables.py")
    print("-- Do not edit manually; re-generate with:")
    print("--   python3 tests/gen_wide_tables.py > tests/bench_setup_wide.sql")
    print("")
    print("\\timing on")
    print("")

    for name, ncols, nrows in CONFIGS:
        print(generate_table(name, ncols, nrows))

    print("\\echo 'Wide table setup complete.'")
    print("\\timing off")


if __name__ == "__main__":
    main()
