name: "PG 17 \xB7 Windows x86_64"
on:
  push:
    branches: [master]
    paths-ignore: ['**.md', 'LICENSE', '.gitignore', 'tests/**', 'img/**', 'bench/**']
  pull_request:
    paths-ignore: ['**.md', 'LICENSE', '.gitignore', 'tests/**', 'img/**', 'bench/**']
jobs:
  build:
    uses: ./.github/workflows/build-reusable.yml
    with:
      postgres-version: "17"
      os: windows-2022
